### ISSUE TITLE
Сверстать страницу регистрации

### ISSUE THREAD

**Issue by SashaLevkovich** [SashaLevkovich/middle.SandwormRampage.praktikum.yandex#10]
**Актуальный дизайн:** [https://www.figma.com/design/C7ZNepiy6l0NfTYEygPAju/Gamedev?node-id=2-2&t=z9KnitmN8J0B3hXA-4](https://www.figma.com/design/C7ZNepiy6l0NfTYEygPAju/Gamedev?node-id=2-2&t=z9KnitmN8J0B3hXA-4)

---

## **Ожидание:**

Регистрация с формой, имена полей: `first_name`, `second_name`, `login`, `email`, `password`, `phone`.

**Comment by Pillowbee** [comment]
> **Актуальный дизайн:** https://www.figma.com/design/C7ZNepiy6l0NfTYEygPAju/Gamedev?node-id=2-2&t=z9KnitmN8J0B3hXA-4
> 
> ## **Ожидание:**
> Регистрация с формой, имена полей: `first_name`, `second_name`, `login`, `email`, `password`, `phone`.

В дизайне другие поля
